import { expect } from "chai";
import fs from "node:fs";
import path from "node:path";
import hre from "hardhat";
import { getCreateAddress, parseEther, formatEther } from "ethers";

// ============================================================================
// CONFIGURATION
// ============================================================================

const DEPLOY_ORDER = [
  "ICONS_32",
  "TROPHY_SVG_ASSETS",
  "GAME_MINT_MODULE",
  "GAME_JACKPOT_MODULE",
  "GAME_ENDGAME_MODULE",
  "COIN",
  "VAULT",
  "AFFILIATE",
  "JACKPOTS",
  "QUESTS",
  "ICON_COLOR_REGISTRY",
  "RENDERER_REGULAR",
  "RENDERER_TROPHY_SVG",
  "RENDERER_TROPHY",
  "GAMEPIECE_RENDERER_ROUTER",
  "TROPHY_RENDERER_ROUTER",
  "TROPHIES",
  "GAMEPIECES",
  "GAME",
  "ADMIN"
];

const ALL_CONSTANTS = [...DEPLOY_ORDER, "STETH_TOKEN", "LINK_TOKEN", "CREATOR", "VRF_COORDINATOR", "VRF_KEY_HASH"];
const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";
const ZERO_BYTES32 = "0x0000000000000000000000000000000000000000000000000000000000000000";
const MOCK_KEY_HASH = "0x0000000000000000000000000000000000000000000000000000000000000001"; // Non-zero for testing
const JACKPOT_RESET_TIME = 82620;
const SECONDS_PER_DAY = 24 * 60 * 60;

// Game state constants from DegenerusGameStorage.sol
const GAME_STATE = {
  SETUP: 1,
  PURCHASE: 2,
  BURN: 3,
  GAMEOVER: 86
};

// Purchase enums from contracts
const PURCHASE_KIND = {
  Player: 0,
  Map: 1
};

const MINT_PAYMENT_KIND = {
  DirectEth: 0,
  Claimable: 1,
  Combined: 2
};

// Simulation seed amounts for BAF/Decimator coverage (BURNIE, 18 decimals)
const BAF_DEPOSIT_AMOUNT = parseEther("6000");
const DECIMATOR_BURN_AMOUNT = parseEther("1000");
const BAF_SEED_AMOUNT = parseEther("8000");
const DECIMATOR_SEED_AMOUNT = parseEther("2000");
const MAP_BATCH_CAP = 780; // Default safe writes budget for processMapBatch

// ============================================================================
// UTILITIES
// ============================================================================

function renderSolidity(constants) {
  const lines = [
    "// SPDX-License-Identifier: MIT",
    "pragma solidity ^0.8.26;",
    "",
    "// AUTO-GENERATED by test/full-simulation.test.js",
    "// Do not edit by hand; regenerate via the test.",
    "library ContractAddresses {"
  ];

  for (const name of ALL_CONSTANTS) {
    if (name === "VRF_KEY_HASH") {
      const value = constants[name] || ZERO_BYTES32;
      lines.push(`    bytes32 internal constant ${name} = ${value};`);
    } else {
      const value = constants[name] || ZERO_ADDRESS;
      lines.push(`    address internal constant ${name} = ${value};`);
    }
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

async function deployAll(ethers, deployer, expected) {
  const deployed = {};
  const iconsPath = path.resolve("scripts/data/icons32Data.json");
  const iconsData = JSON.parse(fs.readFileSync(iconsPath, "utf8"));

  console.log("\n=== DEPLOYING CONTRACTS ===\n");

  for (const name of DEPLOY_ORDER) {
    let factory;
    let args = [];

    if (name === "ICONS_32") {
      factory = await ethers.getContractFactory("contracts/Icons32Data.sol:Icons32Data", deployer);
      args = [iconsData.paths, iconsData.diamond, iconsData.symQ1, iconsData.symQ2, iconsData.symQ3];
    } else if (name === "TROPHY_SVG_ASSETS") {
      factory = await ethers.getContractFactory("contracts/TrophySvgAssets.sol:TrophySvgAssets", deployer);
    } else if (name === "GAME_MINT_MODULE") {
      factory = await ethers.getContractFactory(
        "contracts/modules/DegenerusGameMintModule.sol:DegenerusGameMintModule",
        deployer
      );
    } else if (name === "GAME_JACKPOT_MODULE") {
      factory = await ethers.getContractFactory(
        "contracts/modules/DegenerusGameJackpotModule.sol:DegenerusGameJackpotModule",
        deployer
      );
    } else if (name === "GAME_ENDGAME_MODULE") {
      factory = await ethers.getContractFactory(
        "contracts/modules/DegenerusGameEndgameModule.sol:DegenerusGameEndgameModule",
        deployer
      );
    } else if (name === "VAULT") {
      factory = await ethers.getContractFactory("contracts/DegenerusVault.sol:DegenerusVault", deployer);
    } else if (name === "COIN") {
      factory = await ethers.getContractFactory("contracts/BurnieCoin.sol:BurnieCoin", deployer);
    } else if (name === "AFFILIATE") {
      factory = await ethers.getContractFactory("contracts/DegenerusAffiliate.sol:DegenerusAffiliate", deployer);
    } else if (name === "JACKPOTS") {
      factory = await ethers.getContractFactory("contracts/DegenerusJackpots.sol:DegenerusJackpots", deployer);
    } else if (name === "QUESTS") {
      factory = await ethers.getContractFactory("contracts/DegenerusQuests.sol:DegenerusQuests", deployer);
    } else if (name === "ICON_COLOR_REGISTRY") {
      factory = await ethers.getContractFactory("contracts/IconColorRegistry.sol:IconColorRegistry", deployer);
    } else if (name === "RENDERER_REGULAR") {
      factory = await ethers.getContractFactory("contracts/IconRendererRegular32.sol:IconRendererRegular32", deployer);
    } else if (name === "RENDERER_TROPHY_SVG") {
      factory = await ethers.getContractFactory("contracts/IconRendererTrophy32Svg.sol:IconRendererTrophy32Svg", deployer);
    } else if (name === "RENDERER_TROPHY") {
      factory = await ethers.getContractFactory("contracts/IconRendererTrophy32.sol:IconRendererTrophy32", deployer);
    } else if (name === "GAMEPIECE_RENDERER_ROUTER") {
      factory = await ethers.getContractFactory("contracts/GamepieceRendererRouter.sol:GamepieceRendererRouter", deployer);
    } else if (name === "TROPHY_RENDERER_ROUTER") {
      factory = await ethers.getContractFactory("contracts/TrophyRendererRouter.sol:TrophyRendererRouter", deployer);
    } else if (name === "TROPHIES") {
      factory = await ethers.getContractFactory("contracts/DegenerusTrophies.sol:DegenerusTrophies", deployer);
    } else if (name === "GAMEPIECES") {
      factory = await ethers.getContractFactory("contracts/DegenerusGamepieces.sol:DegenerusGamepieces", deployer);
    } else if (name === "GAME") {
      factory = await ethers.getContractFactory("contracts/DegenerusGame.sol:DegenerusGame", deployer);
    } else if (name === "ADMIN") {
      factory = await ethers.getContractFactory("contracts/DegenerusAdmin.sol:DegenerusAdmin", deployer);
    } else {
      throw new Error(`Unknown deploy target: ${name}`);
    }

    console.log(`Deploying ${name}...`);
    const contract = await factory.deploy(...args);
    await contract.waitForDeployment();
    const addr = await contract.getAddress();
    expect(addr).to.equal(expected[name]);
    deployed[name] = contract;
    console.log(`  ✓ ${name} deployed at ${addr}`);
  }

  return deployed;
}

async function simulateVRFFulfillment(vrfCoordinator, game, requestId, randomWords) {
  console.log(`  Fulfilling VRF request ${requestId} with random words:`, randomWords);
  const gameAddress = await game.getAddress();
  await vrfCoordinator.fulfillRandomWords(requestId, gameAddress, randomWords);
}

async function logGameState(game, label) {
  const state = await game.gameState();
  const level = await game.level();
  const stateNames = ["", "SETUP", "PURCHASE", "BURN"];
  const stateName = state <= 3 ? stateNames[state] : `UNKNOWN(${state})`;
  console.log(`\n[${label}] Level ${level}, State: ${stateName} (${state})`);
}

async function logPlayerStats(game, gamepieces, coin, player, playerName) {
  const gamepieceBalance = await gamepieces.balanceOf(player.address);
  let coinBalance = 0n;
  try {
    coinBalance = await coin.balanceOf(player.address);
  } catch (e) {
    // Coin might not be initialized yet
  }

  console.log(`  ${playerName}: ${gamepieceBalance} gamepieces, ${formatEther(coinBalance)} BURNIE`);
}

async function advanceTime(seconds) {
  await ethers.provider.send("evm_increaseTime", [seconds]);
  await ethers.provider.send("evm_mine", []);
}

async function currentDayIndex() {
  const block = await hre.ethers.provider.getBlock("latest");
  return Math.floor((block.timestamp - JACKPOT_RESET_TIME) / SECONDS_PER_DAY);
}

async function readGameSlot0(game) {
  const addr = await game.getAddress();
  const slot0 = await hre.ethers.provider.getStorage(addr, 0);
  const value = BigInt(slot0);
  const mask48 = (1n << 48n) - 1n;
  const mask32 = (1n << 32n) - 1n;
  const mask24 = (1n << 24n) - 1n;
  const mask16 = (1n << 16n) - 1n;
  const mask8 = (1n << 8n) - 1n;

  return {
    levelStartTime: value & mask48,
    dailyIdx: (value >> 48n) & mask48,
    rngRequestTime: (value >> 96n) & mask48,
    airdropMapsProcessedCount: (value >> 144n) & mask32,
    airdropIndex: (value >> 176n) & mask32,
    level: (value >> 208n) & mask24,
    lastExterminatedTrait: (value >> 232n) & mask16,
    gameState: (value >> 248n) & mask8
  };
}

async function logRngDebug(game, label) {
  const day = await currentDayIndex();
  const dayWord = await game.rngWordForDay(BigInt(day));
  const lastWord = await game.lastRngWord();
  const rngLocked = await game.rngLocked();
  const rngFulfilled = await game.isRngFulfilled();
  const slot0 = await readGameSlot0(game);

  console.log(
    `  🔎 RNG ${label}: day=${day} dailyIdx=${slot0.dailyIdx} locked=${rngLocked} fulfilled=${rngFulfilled} dayWord=${dayWord} lastWord=${lastWord} vrfReqTime=${slot0.rngRequestTime}`
  );
}

async function fulfillVrfIfRequested(vrfCoordinator, game) {
  const latestBlock = await hre.ethers.provider.getBlockNumber();
  const fromBlock = Math.max(latestBlock - 1, 0);
  const vrfRequestFilter = vrfCoordinator.filters.RandomWordsRequested();
  const events = await vrfCoordinator.queryFilter(vrfRequestFilter, fromBlock, latestBlock);

  if (events.length === 0) return false;

  const gameAddress = await game.getAddress();
  for (const event of events) {
    const requestId = event.args.requestId;
    const requester = event.args.sender;
    if (requester && requester.toLowerCase() !== gameAddress.toLowerCase()) {
      continue;
    }
    const request = await vrfCoordinator.s_requests(requestId);
    if (!request.fulfilled) {
      const randomWords = [BigInt("0x" + Math.floor(Math.random() * Number.MAX_SAFE_INTEGER).toString(16))];
      await vrfCoordinator.fulfillRandomWords(requestId, gameAddress, randomWords);
      console.log(`    🎲 VRF fulfilled: request ${requestId}`);
    }
  }

  return true;
}

async function logFinancialState(game, vault, gamepieces, coin, mockStEth, label) {
  console.log(`\n╔════════════════════════════════════════════════════════════════╗`);
  console.log(`║  ${label.padEnd(62)} ║`);
  console.log(`╚════════════════════════════════════════════════════════════════╝`);

  // Get contract balances
  const gameAddress = await game.getAddress();
  const vaultAddress = await vault.getAddress();

  const gameEthBalance = await hre.ethers.provider.getBalance(gameAddress);
  const gameStEthBalance = await mockStEth.balanceOf(gameAddress);
  const vaultEthBalance = await hre.ethers.provider.getBalance(vaultAddress);
  const vaultStEthBalance = await mockStEth.balanceOf(vaultAddress);

  // Token supplies
  const totalBurnie = await coin.totalSupply();

  // Prize pools
  const nextPool = await game.nextPrizePoolView();
  const poolTarget = await game.prizePoolTargetView();

  // Gamepieces stats
  const totalGamepieces = await gamepieces.totalSupply();

  console.log(`\n━━━ CONTRACT BALANCES ━━━`);
  console.log(`  Game Contract:`);
  console.log(`    ETH:                    ${formatEther(gameEthBalance).padStart(12)} ETH`);
  console.log(`    stETH:                  ${formatEther(gameStEthBalance).padStart(12)} stETH`);
  console.log(`    Combined:               ${formatEther(gameEthBalance + gameStEthBalance).padStart(12)} ETH`);

  console.log(`\n  Vault Contract:`);
  console.log(`    ETH:                    ${formatEther(vaultEthBalance).padStart(12)} ETH`);
  console.log(`    stETH:                  ${formatEther(vaultStEthBalance).padStart(12)} stETH`);
  console.log(`    Combined:               ${formatEther(vaultEthBalance + vaultStEthBalance).padStart(12)} ETH`);

  console.log(`\n━━━ PRIZE POOLS ━━━`);
  console.log(`  Next Prize Pool:          ${formatEther(nextPool).padStart(12)} ETH`);
  console.log(`  Pool Target:              ${formatEther(poolTarget).padStart(12)} ETH`);
  console.log(`  Target Met:               ${nextPool >= poolTarget ? '✅ YES' : '❌ NO'}`);

  console.log(`\n━━━ TOKEN SUPPLIES ━━━`);
  console.log(`  BURNIE Coin:              ${formatEther(totalBurnie).padStart(12)} BURNIE`);

  console.log(`\n━━━ GAME STATE ━━━`);
  const currentLevel = await game.level();
  const currentState = await game.gameState();
  const stateNames = ['', 'SETUP', 'PURCHASE', 'BURN'];
  console.log(`  Level:                    ${currentLevel}`);
  console.log(`  State:                    ${stateNames[Number(currentState)] || currentState}`);
  console.log(`  Total Gamepieces:         ${totalGamepieces}`);

  const totalSystemEth = gameEthBalance + gameStEthBalance + vaultEthBalance + vaultStEthBalance;
  console.log(`\n━━━ TOTAL SYSTEM VALUE ━━━`);
  console.log(`  Total ETH+stETH:          ${formatEther(totalSystemEth).padStart(12)} ETH`);
  console.log(``);
}

async function logPrizePools(game, label) {
  const target = await game.prizePoolTargetView();
  const next = await game.nextPrizePoolView();
  console.log(
    `  🎯 ${label}: nextPrizePool=${formatEther(next)} ETH target=${formatEther(target)} ETH met=${next >= target}`
  );
}

function toBigInt(value) {
  return typeof value === "bigint" ? value : BigInt(value.toString());
}

async function collectTokensForPlayers(gamepieces, players, fromBlock) {
  const latestBlock = await hre.ethers.provider.getBlockNumber();
  const transfers = await gamepieces.queryFilter(gamepieces.filters.Transfer(), fromBlock, latestBlock);
  const ownership = new Map();

  for (const event of transfers) {
    const args = event.args || {};
    const tokenIdRaw = args.tokenId ?? args[2];
    const toRaw = args.to ?? args[1];
    if (tokenIdRaw === undefined || !toRaw) continue;

    const tokenKey = toBigInt(tokenIdRaw).toString();
    const to = toRaw.toLowerCase();
    if (to === ZERO_ADDRESS) {
      ownership.delete(tokenKey);
    } else {
      ownership.set(tokenKey, to);
    }
  }

  const baseTokenId = await gamepieces.currentBaseTokenId();
  const tokensByPlayer = new Map();
  for (const player of players) {
    tokensByPlayer.set(player.address.toLowerCase(), []);
  }

  for (const [tokenIdStr, owner] of ownership.entries()) {
    const tokenId = BigInt(tokenIdStr);
    if (tokenId < baseTokenId) continue;
    const list = tokensByPlayer.get(owner);
    if (list) list.push(tokenId);
  }

  for (const list of tokensByPlayer.values()) {
    list.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  }

  return { tokenIdsByPlayer: tokensByPlayer, latestBlock, baseTokenId };
}

// ============================================================================
// MAIN SIMULATION TEST
// ============================================================================

describe("Full On-Chain Simulation: Deployment → Gameplay → Level 12", function () {
  let ethers, deployer, aux;
  let players = [];
  let affiliate; // Affiliate account that refers all players
  let contracts = {};
  let mockStEth, mockLink, vrfCoordinator;
  let game, gamepieces, coin, admin, vault, jackpots, trophies, affiliateContract;
  let affiliateCode; // Affiliate code hash
  let bafPlayer;
  let decimatorPlayer;

  this.timeout(600000); // 10 minutes timeout for full simulation

  // Helper function to handle VRF fulfillment (shared across all tests)
  async function fulfillVRFIfNeeded() {
    const gameAddress = await game.getAddress();
    const latestBlock = await ethers.provider.getBlockNumber();
    const vrfRequestFilter = vrfCoordinator.filters.RandomWordsRequested();
    const events = await vrfCoordinator.queryFilter(vrfRequestFilter, latestBlock - 1, latestBlock);

    if (events.length > 0) {
      const requestId = events[0].args.requestId;
      console.log(`    🎲 VRF requested: ${requestId}`);
      const randomWords = [
        BigInt("0x" + Math.floor(Math.random() * Number.MAX_SAFE_INTEGER).toString(16)),
        BigInt("0x" + Math.floor(Math.random() * Number.MAX_SAFE_INTEGER).toString(16))
      ];
      await vrfCoordinator.fulfillRandomWords(requestId, gameAddress, randomWords);
      console.log(`    ✓ VRF fulfilled`);
      return true;
    }
    return false;
  }

  before(async function () {
    console.log("\n╔════════════════════════════════════════════════════════════════╗");
    console.log("║  FULL ON-CHAIN SIMULATION: DEPLOYMENT → GAMEPLAY → LEVEL 12   ║");
    console.log("╚════════════════════════════════════════════════════════════════╝\n");

    ({ ethers, run } = hre);
    const signers = await ethers.getSigners();
    deployer = signers[0];
    aux = signers[1];
    affiliate = signers[2]; // Affiliate account

    // Create 10 player accounts (starting from index 3)
    for (let i = 3; i < 13; i++) {
      players.push(signers[i]);
    }

    // Generate affiliate code (keccak256 of affiliate address)
    affiliateCode = ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(['address'], [affiliate.address]));

    console.log(`Deployer: ${deployer.address}`);
    console.log(`Affiliate: ${affiliate.address}`);
    console.log(`Affiliate Code: ${affiliateCode}`);
    console.log(`Players: ${players.length} accounts\n`);
  });

  it("Step 1: Deploy mock tokens and VRF coordinator", async function () {
    console.log("\n=== STEP 1: DEPLOYING MOCKS ===\n");

    // Deploy MockStETH
    const mockStEthFactory = await ethers.getContractFactory("contracts/test/MockStETH.sol:MockStETH", aux);
    mockStEth = await mockStEthFactory.deploy();
    await mockStEth.waitForDeployment();
    console.log(`MockStETH deployed at ${await mockStEth.getAddress()}`);

    // Deploy MockLink
    const mockLinkFactory = await ethers.getContractFactory("contracts/test/MockLink.sol:MockLink", aux);
    mockLink = await mockLinkFactory.deploy();
    await mockLink.waitForDeployment();
    console.log(`MockLink deployed at ${await mockLink.getAddress()}`);

    // Deploy VRF Coordinator Mock
    const vrfFactory = await ethers.getContractFactory("contracts/test/VRFCoordinatorV2_5Mock.sol:VRFCoordinatorV2_5Mock", aux);
    vrfCoordinator = await vrfFactory.deploy(
      parseEther("0.000001"), // 0.000001 LINK base fee
      1000000000, // gas price 1 gwei
      parseEther("0.000001") // 0.000001 LINK per gas
    );
    await vrfCoordinator.waitForDeployment();
    console.log(`VRFCoordinatorV2_5Mock deployed at ${await vrfCoordinator.getAddress()}`);
  });

  it("Step 2: Precompute addresses and deploy all contracts", async function () {
    console.log("\n=== STEP 2: PRECOMPUTING ADDRESSES ===\n");

    const startNonce = await deployer.getNonce();
    const expected = {};
    let nonce = startNonce;

    for (const name of DEPLOY_ORDER) {
      expected[name] = getCreateAddress({ from: deployer.address, nonce });
      nonce += 1;
    }

    expected.STETH_TOKEN = await mockStEth.getAddress();
    expected.LINK_TOKEN = await mockLink.getAddress();
    expected.CREATOR = deployer.address;
    expected.VRF_COORDINATOR = await vrfCoordinator.getAddress();
    expected.VRF_KEY_HASH = MOCK_KEY_HASH; // Non-zero key hash required

    console.log("Writing ContractAddresses.sol...");
    const output = path.resolve("contracts/ContractAddresses.sol");
    fs.writeFileSync(output, renderSolidity(expected), "utf8");

    console.log("Compiling contracts...");
    await run("compile");

    contracts = await deployAll(ethers, deployer, expected);

    // Store frequently used contracts
    game = contracts.GAME;
    gamepieces = contracts.GAMEPIECES;
    coin = contracts.COIN;
    admin = contracts.ADMIN;
    vault = contracts.VAULT;
    jackpots = contracts.JACKPOTS;
    trophies = contracts.TROPHIES;
    affiliateContract = contracts.AFFILIATE;

    console.log("\n✓ All contracts deployed successfully!");
  });

  it("Step 3: Fund deployer with LINK for VRF", async function () {
    console.log("\n=== STEP 3: FUNDING VRF SUBSCRIPTION ===\n");

    // Create VRF subscription
    const subId = 1n; // Mock VRF coordinator starts at 1
    await vrfCoordinator.createSubscription();
    console.log(`VRF Subscription created: ${subId}`);

    // Fund subscription with LINK
    const linkAmount = parseEther("100");
    await mockLink.connect(aux).mint(deployer.address, linkAmount);
    await mockLink.connect(deployer).transferAndCall(
      await vrfCoordinator.getAddress(),
      linkAmount,
      ethers.AbiCoder.defaultAbiCoder().encode(["uint256"], [subId])
    );
    console.log(`Subscription funded with ${formatEther(linkAmount)} LINK`);

    // Add game as consumer
    await vrfCoordinator.addConsumer(subId, await game.getAddress());
    console.log(`Game added as VRF consumer`);
  });

  it("Step 4: Verify VRF configuration", async function () {
    console.log("\n=== STEP 4: VERIFYING VRF CONFIGURATION ===\n");

    // VRF was already wired during Admin contract construction
    const vrfAddress = await vrfCoordinator.getAddress();
    const subId = await admin.subscriptionId();

    console.log(`VRF Coordinator: ${vrfAddress}`);
    console.log(`Subscription ID: ${subId}`);

    // Check if Game contract has VRF wired
    try {
      const gameVrfSub = await game.vrfSubscriptionId();
      console.log(`Game VRF Subscription ID: ${gameVrfSub}`);
      if (gameVrfSub === 0n) {
        console.log("⚠ WARNING: Game VRF not wired! Subscription ID is 0");
      }
    } catch (e) {
      console.log(`⚠ Cannot read game VRF config: ${e.message}`);
    }

    console.log("✓ VRF configuration verified");
  });

  it("Step 5: Create affiliate code", async function () {
    console.log("\n=== STEP 5: CREATE AFFILIATE CODE ===\n");

    try {
      await affiliateContract.connect(affiliate).createAffiliateCode(affiliateCode, 25);
      console.log("✓ Affiliate code created (25% rakeback)");
    } catch (error) {
      console.log(`⚠ Affiliate code create failed: ${error.message.substring(0, 80)}`);
    }

    // Set BAF and Decimator players for later use
    bafPlayer = players[0];
    decimatorPlayer = players[1];
    console.log(`BAF player: ${bafPlayer.address}`);
    console.log(`Decimator player: ${decimatorPlayer.address}`);
  });

  it("Step 6: Players purchase MAPs", async function () {
    console.log("\n=== STEP 6: MAP PURCHASES ===\n");
    console.log("Each player purchases 10 ETH worth of MAPs (jackpot tickets without gamepieces)\n");

    const mapAmount = parseEther("10.0");
    let totalMapPurchases = 0n;

    const mintPrice = await game.mintPrice();
    const mapPrice = mintPrice / 4n;
    const mapQuantity = mapAmount / mapPrice;

    console.log(`MAP price: ${formatEther(mapPrice)} ETH per unit`);
    console.log(`Purchasing ${mapQuantity} MAP units for ${formatEther(mapAmount)} ETH\n`);

    for (let i = 0; i < players.length; i++) {
      const player = players[i];
      console.log(`Player ${i} purchasing ${mapQuantity} MAPs...`);

      const purchaseParams = {
        quantity: Number(mapQuantity),
        kind: PURCHASE_KIND.Map,
        payKind: MINT_PAYMENT_KIND.DirectEth,
        payInCoin: false,
        affiliateCode: affiliateCode
      };

      await gamepieces.connect(player).purchase(purchaseParams, { value: mapAmount });
      totalMapPurchases += mapAmount;
      console.log(`  ✓ Player ${i} purchased successfully`);
    }

    console.log(`\n✓ Total MAP purchases: ${formatEther(totalMapPurchases)} ETH`);

    // Process MAP batches - call advance once per day until RNG unlocks
    console.log(`\n📦 Processing MAP batches...`);

    for (let day = 0; day < 200; day++) {
      // Check if done
      const rngLocked = await game.rngLocked();
      if (!rngLocked) {
        console.log(`✓ MAP batches complete after ${day} days`);
        break;
      }

      // Advance 24 hours
      await ethers.provider.send("evm_increaseTime", [24 * 60 * 60]);
      await ethers.provider.send("evm_mine", []);

      console.log(`  Day ${day + 1}: calling advanceGame(${MAP_BATCH_CAP})...`);

      try {
        await game.connect(deployer).advanceGame(MAP_BATCH_CAP);
        console.log(`    ✓ advanceGame succeeded`);
      } catch (error) {
        console.log(`    ❌ advanceGame failed: ${error.message.substring(0, 100)}`);

        // Check for VRF and fulfill
        const latestBlock = await ethers.provider.getBlockNumber();
        const vrfRequestFilter = vrfCoordinator.filters.RandomWordsRequested();
        const events = await vrfCoordinator.queryFilter(vrfRequestFilter, 0, latestBlock);

        if (events.length > 0) {
          for (const event of events) {
            const requestId = event.args.requestId;
            const request = await vrfCoordinator.s_requests(requestId);
            if (!request.fulfilled) {
              const gameAddress = await game.getAddress();
              const randomWords = [
                BigInt("0x" + Math.floor(Math.random() * Number.MAX_SAFE_INTEGER).toString(16)),
                BigInt("0x" + Math.floor(Math.random() * Number.MAX_SAFE_INTEGER).toString(16))
              ];
              await vrfCoordinator.fulfillRandomWords(requestId, gameAddress, randomWords);
              console.log(`    🎲 VRF fulfilled: request ${requestId}`);
            }
          }
        }
      }
    }

    await logFinancialState(game, vault, gamepieces, coin, mockStEth, "FINANCIAL STATE: AFTER MAP PURCHASES");
  });

  it("Step 7: Progress through gameplay levels organically", async function () {
    console.log("\n=== STEP 7: GAMEPLAY SIMULATION (LEVELS 1-12) ===\n");

    let bafFlipSeeded = false;
    let decimatorBurned = false;
    let tracedAdvanceRevert = false;
    let failFastAdvance = true;
    let purchaseLevel = null;

    const ifaceByAddress = new Map();
    const nameByAddress = new Map();
    const registerContract = async (name, contract) => {
      const addr = (await contract.getAddress()).toLowerCase();
      ifaceByAddress.set(addr, contract.interface);
      nameByAddress.set(addr, name);
    };

    await registerContract("game", game);
    await registerContract("gamepieces", gamepieces);
    await registerContract("coin", coin);
    await registerContract("vault", vault);
    await registerContract("jackpots", jackpots);
    await registerContract("trophies", trophies);
    await registerContract("affiliate", affiliateContract);
    await registerContract("gameJackpotModule", contracts.GAME_JACKPOT_MODULE);
    await registerContract("gameMintModule", contracts.GAME_MINT_MODULE);
    await registerContract("gameEndgameModule", contracts.GAME_ENDGAME_MODULE);

    async function traceAdvanceRevert(txHash) {
      if (tracedAdvanceRevert || !txHash) return;
      tracedAdvanceRevert = true;
      try {
        let trace;
        try {
          trace = await hre.network.provider.send("debug_traceTransaction", [
            txHash,
            { disableStack: true, disableStorage: true, disableMemory: true }
          ]);
        } catch {
          trace = await hre.network.provider.send("debug_traceTransaction", [txHash]);
        }
        const returnValue = trace?.returnValue;
        if (!returnValue || returnValue === "0x") {
          console.log("  ↳ trace: no revert data");
        } else {
          let decoded = null;
          let decodedSource = null;
          for (const [addr, iface] of ifaceByAddress.entries()) {
            try {
              decoded = iface.parseError(returnValue);
              decodedSource = nameByAddress.get(addr) || addr;
              break;
            } catch {}
          }
          if (decoded) {
            console.log(
              `  ↳ revert: ${decoded.name}(${decoded.args.map((arg) => arg.toString()).join(", ")}) @ ${decodedSource}`
            );
          } else {
            console.log(`  ↳ revert data: ${returnValue}`);
          }
        }
        try {
          const callTrace = await hre.network.provider.send("debug_traceTransaction", [
            txHash,
            { tracer: "callTracer" }
          ]);
          const findDeepestError = (call) => {
            if (!call) return null;
            const calls = call.calls || [];
            for (const child of calls) {
              const found = findDeepestError(child);
              if (found) return found;
            }
            if (call.error) return call;
            return null;
          };
          const failing = findDeepestError(callTrace);
          if (failing) {
            const to = failing.to?.toLowerCase();
            const name = to ? nameByAddress.get(to) : null;
            const iface = to ? ifaceByAddress.get(to) : null;
            const selector = failing.input ? failing.input.slice(0, 10) : null;
            let funcName = null;
            if (iface && selector) {
              try {
                funcName = iface.getFunction(selector)?.name || null;
              } catch {}
            }
            console.log(`  ↳ callTrace error: ${failing.error}`);
            if (to) {
              console.log(`  ↳ callTrace to: ${name || to}`);
            }
            if (selector) {
              console.log(`  ↳ callTrace selector: ${selector}${funcName ? ` (${funcName})` : ""}`);
            }
            if (failing.output && failing.output !== "0x") {
              let decodedError = null;
              if (iface) {
                try {
                  decodedError = iface.parseError(failing.output);
                } catch {}
              }
              if (decodedError) {
                console.log(
                  `  ↳ callTrace decoded: ${decodedError.name}(${decodedError.args
                    .map((arg) => arg.toString())
                    .join(", ")})`
                );
              } else {
                console.log(`  ↳ callTrace output: ${failing.output}`);
              }
            }
          } else {
            console.log("  ↳ callTrace: no error found");
          }
        } catch (traceError) {
          console.log(`  ↳ callTrace failed: ${traceError.message.substring(0, 120)}`);
        }
      } catch (traceError) {
        console.log(`  ↳ trace failed: ${traceError.message.substring(0, 120)}`);
      }
    }

    async function logAdvanceError(label, error, txHash) {
      const message = error?.shortMessage || error?.message || "Unknown error";
      console.log(`  ❌ ${label} failed: ${message}`);
      if (txHash) {
        console.log(`  ↳ tx: ${txHash}`);
      }
      const data =
        error?.data ||
        error?.error?.data ||
        error?.info?.error?.data ||
        error?.info?.data ||
        error?.revert?.data ||
        null;
      if (error?.info?.error?.message) {
        console.log(`  ↳ info: ${error.info.error.message}`);
      }
      if (error?.code) {
        console.log(`  ↳ code: ${error.code}`);
      }
      if (error?.receipt?.gasUsed) {
        console.log(`  ↳ gas used: ${error.receipt.gasUsed.toString()}`);
      }
      if (error?.receipt?.status !== undefined) {
        console.log(`  ↳ status: ${error.receipt.status}`);
      }
      if (!error?.receipt) {
        console.log("  ↳ no receipt on error");
        if (txHash) {
          const fetched = await hre.ethers.provider.getTransactionReceipt(txHash);
          if (fetched) {
            console.log(`  ↳ receipt status: ${fetched.status}`);
            console.log(`  ↳ receipt gasUsed: ${fetched.gasUsed.toString()}`);
          }
        }
      }
      if (data && data !== "0x") {
        try {
          const decoded = game.interface.parseError(data);
          console.log(`  ↳ ${decoded.name}(${decoded.args.map((arg) => arg.toString()).join(", ")})`);
        } catch {
          console.log(`  ↳ raw revert data: ${data}`);
        }
      }
      await logRngDebug(game, "after revert");
      await traceAdvanceRevert(txHash);
    }

    async function safeAdvanceGame(signer, cap, label) {
      try {
        const tx = await signer.sendTransaction({
          to: await game.getAddress(),
          data: game.interface.encodeFunctionData("advanceGame", [cap]),
          gasLimit: 30_000_000n
        });
        const receipt = await tx.wait();
        console.log(`    ⛽ ${label} gas: ${receipt.gasUsed.toString()}`);
        return true;
      } catch (error) {
        const txHash = error?.transactionHash || error?.hash || error?.info?.hash || null;
        await logAdvanceError(label, error, txHash);
        if (failFastAdvance) {
          failFastAdvance = false;
          throw error;
        }
        return false;
      }
    }

    async function maybeDecimatorBurn() {
      if (decimatorBurned || !decimatorPlayer) return;
      const [decOn, decLvl] = await game.decWindow();
      if (!decOn || decLvl !== 5n) return;

      console.log(`\n🔥 Decimator window open (level ${decLvl}). Attempting to burn ${formatEther(DECIMATOR_BURN_AMOUNT)} BURNIE...`);
      const balance = await coin.balanceOf(decimatorPlayer.address);
      console.log(`  Decimator player balance: ${formatEther(balance)} BURNIE`);

      if (balance >= DECIMATOR_BURN_AMOUNT) {
        await coin.connect(decimatorPlayer).decimatorBurn(DECIMATOR_BURN_AMOUNT);
        decimatorBurned = true;
        console.log(`  ✓ Decimator burn submitted`);
      } else {
        console.log(`  ⚠ Insufficient balance (need ${formatEther(DECIMATOR_BURN_AMOUNT)}, have ${formatEther(balance)})`);
        console.log(`  ⚠ Skipping decimator burn`);
      }
    }

    // Check if RNG is locked before starting
    const initialRngLocked = await game.rngLocked();
    console.log(`\n🔍 Initial RNG status: ${initialRngLocked ? 'LOCKED' : 'UNLOCKED'}`);

    if (initialRngLocked) {
      console.log(`⚠ RNG is locked! Attempting to unlock with deployer...`);
      // Force unlock by calling advanceGame multiple times with cap=100
      for (let i = 0; i < 20; i++) {
        try {
          await game.connect(deployer).advanceGame(100);
          const rngLocked = await game.rngLocked();
          if (!rngLocked) {
            console.log(`✓ RNG unlocked after ${i + 1} advances`);
            break;
          }
        } catch (e) {
          // Continue trying
        }
      }
    }

    // Helper to advance game with VRF handling
    async function advanceGameWithVRF(maxAttempts = 5) {
      for (let attempt = 0; attempt < maxAttempts; attempt++) {
        await game.advanceGame(100);

        // Check for VRF request
        const latestBlock = await ethers.provider.getBlockNumber();
        const vrfRequestFilter = vrfCoordinator.filters.RandomWordsRequested();
        const events = await vrfCoordinator.queryFilter(vrfRequestFilter, latestBlock - 1, latestBlock);

        if (events.length > 0) {
          const requestId = events[0].args.requestId;
          const randomWords = [
            BigInt("0x" + Math.floor(Math.random() * Number.MAX_SAFE_INTEGER).toString(16)),
            BigInt("0x" + Math.floor(Math.random() * Number.MAX_SAFE_INTEGER).toString(16))
          ];
          const gameAddress = await game.getAddress();
          await vrfCoordinator.fulfillRandomWords(requestId, gameAddress, randomWords);

          // Advance again after VRF
          await game.advanceGame(100);

          // Check if still need more advances (MAP jackpot queued)
          const rngLocked = await game.rngLocked();
          if (rngLocked) {
            continue; // Need another round
          }
        }

        // RNG unlocked, done
        break;
      }
    }

    let currentLevel = await game.level();
    const targetLevel = 12n;
    const GAME_STATE_GAMEOVER = 86n;
    let safetyCounter = 0;
    const MAX_ITERATIONS = 100; // Safety limit
    let levelStartBlock = await ethers.provider.getBlockNumber();

    while (currentLevel <= targetLevel && safetyCounter < MAX_ITERATIONS) {
      safetyCounter++;

      console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
      console.log(`  LEVEL ${currentLevel}`);
      console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);

      await logGameState(game, `Start of Level ${currentLevel}`);
      await maybeDecimatorBurn();

      // Get current state
      let state = await game.gameState();

      // Check for GAMEOVER
      if (state === GAME_STATE_GAMEOVER) {
        console.log("\n⚠ Game entered GAMEOVER state. Ending simulation.");
        break;
      }

      // PURCHASE PHASE - Players mint gamepieces
      if (state === BigInt(GAME_STATE.PURCHASE)) {
        console.log("\n--- PURCHASE PHASE (Day Phase) ---");

        const mintPrice = await game.mintPrice();
        console.log(`Mint price: ${formatEther(mintPrice)} ETH`);
        await logPrizePools(game, "before purchases");

        if (purchaseLevel !== currentLevel) {
          if (await game.rngLocked()) {
            console.log("  ⚠ RNG locked before purchase, attempting emergency advance...");
            for (let attempt = 0; attempt < 5; attempt++) {
              const ok = await safeAdvanceGame(deployer, MAP_BATCH_CAP, `advanceGame(${MAP_BATCH_CAP})`);
              if (!ok) break;
              await fulfillVrfIfRequested(vrfCoordinator, game);
              if (!(await game.rngLocked())) break;
            }
          }

          if (!(await game.rngLocked())) {
            // Strategy: Buy MAPs to reach ~105% of target, then gamepieces for gameplay
            const targetPool = await game.prizePoolTargetView();
            const nextPool = await game.nextPrizePoolView();
            const desiredPool = (targetPool * 105n) / 100n; // 105% of target
            const deficit = desiredPool > nextPool ? desiredPool - nextPool : 0n;

            console.log(`\n💰 Prize Pool Strategy:`);
            console.log(`  Current: ${formatEther(nextPool)} ETH`);
            console.log(`  Target: ${formatEther(targetPool)} ETH`);
            console.log(`  Desired (105%): ${formatEther(desiredPool)} ETH`);
            console.log(`  Deficit: ${formatEther(deficit)} ETH`);

            if (deficit > 0n) {
              // Buy MAPs to fill deficit (100% of MAP cost → pool)
              const mapPrice = mintPrice / 4n;
              const mapsNeeded = deficit / mapPrice + 1n; // Round up
              const mapsPerPlayer = mapsNeeded / BigInt(players.length) + 1n;
              const mapCostPerPlayer = mapsPerPlayer * mapPrice;

              console.log(`\n  📍 Buying MAPs to reach target:`);
              console.log(`    MAPs needed: ${mapsNeeded} units (${formatEther(deficit)} ETH)`);
              console.log(`    Per player: ${mapsPerPlayer} MAPs for ${formatEther(mapCostPerPlayer)} ETH`);

              for (let i = 0; i < players.length; i++) {
                const player = players[i];
                try {
                  const mapParams = {
                    quantity: Number(mapsPerPlayer),
                    kind: PURCHASE_KIND.Map,
                    payKind: MINT_PAYMENT_KIND.DirectEth,
                    payInCoin: false,
                    affiliateCode: affiliateCode
                  };
                  await gamepieces.connect(player).purchase(mapParams, { value: mapCostPerPlayer });
                  console.log(`    ✓ Player ${i} purchased ${mapsPerPlayer} MAPs`);
                } catch (error) {
                  console.log(`    ⚠ Player ${i} MAP purchase failed: ${error.message.substring(0, 80)}`);
                }
              }
            }

            // Now buy gamepieces for actual gameplay (50-100 per player for faster progression)
            console.log(`\n  🎮 Buying gamepieces for gameplay:`);
            for (let i = 0; i < players.length; i++) {
              const player = players[i];
              const numToMint = 50 + (i % 51); // Mint 50-100 gamepieces per player

              const cost = mintPrice * BigInt(numToMint);
              console.log(`    Player ${i} minting ${numToMint} gamepieces for ${formatEther(cost)} ETH...`);

              try {
                const purchaseParams = {
                  quantity: numToMint,
                  kind: PURCHASE_KIND.Player,
                  payKind: MINT_PAYMENT_KIND.DirectEth,
                  payInCoin: false,
                  affiliateCode: affiliateCode
                };

                await gamepieces.connect(player).purchase(purchaseParams, { value: cost });
                console.log(`    ✓ Player ${i} minted successfully`);
              } catch (error) {
                console.log(`    ⚠ Player ${i} mint failed: ${error.message.substring(0, 100)}`);
              }
            }

            purchaseLevel = currentLevel;
            await logPrizePools(game, "after all purchases");
          } else {
            console.log("  ⚠ RNG still locked, deferring purchases.");
          }
        }

        // Skip to jackpot time (24 hours later)
        console.log("\n⏰ Skipping to jackpot time (24 hours)...");
        await advanceTime(24 * 60 * 60);

        console.log(`⏭ Advancing day with deployer (cap=${MAP_BATCH_CAP}) until RNG unlocked...`);
        try {
          await logRngDebug(game, "before purchase advance");
          for (let attempt = 0; attempt < 50; attempt++) {
            const rngLockedBefore = await game.rngLocked();
            const levelBefore = await game.level();
            const stateBefore = await game.gameState();

            console.log(`  [Attempt ${attempt + 1}] Level: ${levelBefore}, State: ${stateBefore}, RNG locked: ${rngLockedBefore}`);

            const ok = await safeAdvanceGame(deployer, MAP_BATCH_CAP, `advanceGame(${MAP_BATCH_CAP})`);
            if (!ok) break;
            await fulfillVrfIfRequested(vrfCoordinator, game);
            await logRngDebug(game, "after VRF fulfill");

            const rngLocked = await game.rngLocked();
            if (!rngLocked) {
              console.log(`  ✓ RNG unlocked after ${attempt + 1} advance(s)`);
              break;
            }
          }

          state = await game.gameState();
          console.log(`  New state: ${state}`);
          await logPrizePools(game, "after advance");
        } catch (error) {
          console.log(`  ⚠ Advance failed: ${error.message.substring(0, 100)}`);
          throw error;
        }
      }

      // BURN PHASE - Players burn gamepieces for tickets
      if (state === BigInt(GAME_STATE.BURN)) {
        console.log("\n--- BURN PHASE ---");

        let lastBurner = null;
        if (await game.rngLocked()) {
          console.log("  ⚠ RNG locked before burn, attempting to unlock...");
          for (let attempt = 0; attempt < 5; attempt++) {
            const ok = await safeAdvanceGame(deployer, 100, "advanceGame(100)");
            if (!ok) break;
            await fulfillVrfIfRequested(vrfCoordinator, game);
            if (!(await game.rngLocked())) break;
          }
        }

        let tokensByPlayer = null;
        try {
          const snapshot = await collectTokensForPlayers(gamepieces, players, levelStartBlock);
          tokensByPlayer = snapshot.tokenIdsByPlayer;
        } catch (error) {
          console.log(`  ⚠ Token scan failed: ${error.message.substring(0, 100)}`);
        }

        if (tokensByPlayer) {
          for (let pass = 0; pass < 20 && state === BigInt(GAME_STATE.BURN); pass++) {
            let burnedAny = false;
            for (let i = 0; i < players.length && state === BigInt(GAME_STATE.BURN); i++) {
              const player = players[i];
              const tokenIds = tokensByPlayer.get(player.address.toLowerCase()) || [];
              if (tokenIds.length === 0) continue;

              const burnCount = Math.min(75, tokenIds.length);
              const burnBatch = tokenIds.splice(0, burnCount);
              console.log(`Player ${i} burning ${burnBatch.length}/${tokenIds.length + burnBatch.length} gamepieces...`);

              try {
                await game.connect(player).burnTokens(burnBatch);
                lastBurner = player;
                burnedAny = true;
                state = await game.gameState();
              } catch (error) {
                console.log(`  ⚠ Player ${i} burn failed: ${error.message.substring(0, 100)}`);
              }
            }

            if (!burnedAny) {
              console.log("  ⚠ No burnable tokens found for players.");
              break;
            }
          }
        }

        // Skip to jackpot time (24 hours later)
        console.log("\n⏰ Skipping to jackpot time (24 hours)...");
        await advanceTime(24 * 60 * 60);

        // Seed BAF stake one day before level 10 endgame resolution
        if (!bafFlipSeeded && currentLevel === 10n && bafPlayer) {
          console.log(`\n🎯 Seeding BAF coinflip stake for Player 0...`);
          const bafBalance = await coin.balanceOf(bafPlayer.address);
          console.log(`  BAF seed balance: ${formatEther(bafBalance)} BURNIE`);
          await coin.connect(bafPlayer).depositCoinflip(BAF_DEPOSIT_AMOUNT);
          const bafStake = await coin.coinflipAmount(bafPlayer.address);
          console.log(`  ✓ BAF flip stake queued: ${formatEther(bafStake)} BURNIE`);
          bafFlipSeeded = true;
        }

        // Have someone who burned call advanceGame until RNG unlocked
        console.log(`🎲 Triggering jackpot (player calling advanceGame)...`);
        const advanceCaller = lastBurner || deployer;
        try {
          for (let attempt = 0; attempt < 10; attempt++) {
            const ok = await safeAdvanceGame(advanceCaller, 100, "advanceGame(100)");
            if (!ok) break;
            await fulfillVrfIfRequested(vrfCoordinator, game);

            const rngLocked = await game.rngLocked();
            if (!rngLocked) {
              console.log(`  ✓ RNG unlocked after ${attempt + 1} advance(s)`);
              break;
            }
          }

          state = await game.gameState();
          console.log(`  New state: ${state}`);
        } catch (error) {
          console.log(`  ⚠ Jackpot failed: ${error.message.substring(0, 100)}`);
        }
      }

      // SETUP PHASE - Prepare next level
      if (state === BigInt(GAME_STATE.SETUP)) {
        console.log("\n--- SETUP PHASE ---");
        console.log("Processing endgame and setting up next level...");

        // Skip to next day
        console.log("⏰ Skipping to next day (24 hours)...");
        await advanceTime(24 * 60 * 60);

        if (bafFlipSeeded && currentLevel === 11n && bafPlayer) {
          const lastDayStake = await coin.coinflipAmountLastDay(bafPlayer.address);
          const streak = await game.ethMintStreakCount(bafPlayer.address);
          console.log(`  BAF eligibility check: last-day flip ${formatEther(lastDayStake)} BURNIE, mint streak ${streak}`);
        }

        // Use deployer with emergency cap during SETUP to move the state forward.
        console.log("Processing setup transitions...");
        try {
          for (let attempt = 0; attempt < 20; attempt++) {
            await game.connect(deployer).advanceGame(100); // cap=100 bypasses daily gate for setup

            await fulfillVrfIfRequested(vrfCoordinator, game);
            await maybeDecimatorBurn();

            const nextState = await game.gameState();
            if (nextState !== BigInt(GAME_STATE.SETUP)) {
              console.log(`  ✓ Setup complete after ${attempt + 1} advance(s)`);
              state = nextState;
              break;
            }
          }

          state = await game.gameState();
          console.log(`  New state: ${state}`);
        } catch (error) {
          console.log(`  ⚠ Setup failed: ${error.message.substring(0, 100)}`);
        }
      }

      // Update current level
      const newLevel = await game.level();
      if (newLevel === currentLevel) {
        console.log("\n⚠ Level did not advance. State: " + state);

        // Check if we're stuck or just in a multi-phase level
        if (state === BigInt(GAME_STATE.PURCHASE) || state === BigInt(GAME_STATE.BURN) || state === BigInt(GAME_STATE.SETUP)) {
          // Continue to next iteration to process current state
          continue;
        } else {
          console.log(`  ⚠ Unexpected state, stopping simulation at level ${currentLevel}`);
          break;
        }
      }

      currentLevel = newLevel;
      purchaseLevel = null;
      levelStartBlock = await ethers.provider.getBlockNumber();

      // Show financial state every level to track money flows
      if (currentLevel <= targetLevel) {
        await logFinancialState(game, vault, gamepieces, coin, mockStEth, `FINANCIAL STATE: LEVEL ${currentLevel}`);
      }

      if (currentLevel > targetLevel) {
        console.log(`\n✓ Reached target level ${targetLevel}!`);
        break;
      }
    }

    // Check if we hit safety limit
    if (safetyCounter >= MAX_ITERATIONS) {
      console.log(`\n⚠ WARNING: Reached safety limit of ${MAX_ITERATIONS} iterations`);
      console.log(`  Final level: ${currentLevel}, Final state: ${await game.gameState()}`);
    }

    console.log("\n╔════════════════════════════════════════════════════════════════╗");
    console.log("║  SIMULATION COMPLETE!                                          ║");
    console.log("╚════════════════════════════════════════════════════════════════╝");

    // Final financial state
    await logFinancialState(game, vault, gamepieces, coin, mockStEth, "FINAL FINANCIAL STATE");
  });

  it("Step 8: Display final statistics", async function () {
    console.log("\n=== FINAL STATISTICS ===\n");

    const finalLevel = await game.level();
    const finalState = await game.gameState();
    console.log(`Game Level: ${finalLevel}`);
    console.log(`Game State: ${finalState}`);

    console.log("\n--- Player Statistics ---");
    let totalPlayerBurnie = 0n;
    let totalPlayerGamepieces = 0n;

    for (let i = 0; i < players.length; i++) {
      const player = players[i];
      const burnieBalance = await coin.balanceOf(player.address);
      const gamepieceBalance = await gamepieces.balanceOf(player.address);

      totalPlayerBurnie += burnieBalance;
      totalPlayerGamepieces += gamepieceBalance;

      console.log(`\n  Player ${i}:`);
      console.log(`    Gamepieces:  ${gamepieceBalance}`);
      console.log(`    BURNIE:      ${formatEther(burnieBalance)}`);
    }

    console.log(`\n  ━━━ TOTALS ━━━`);
    console.log(`  Total Player Gamepieces: ${totalPlayerGamepieces}`);
    console.log(`  Total Player BURNIE:     ${formatEther(totalPlayerBurnie)}`);

    // Total gamepieces minted
    const totalSupply = await gamepieces.totalSupply();
    console.log(`\n--- NFT Statistics ---`);
    console.log(`Total Gamepieces Minted: ${totalSupply}`);

    // Affiliate statistics
    const affiliateFlipCredits = await coin.coinflipAmount(affiliate.address);
    const affiliateBurnie = await coin.balanceOf(affiliate.address);
    console.log(`\n--- Affiliate Statistics ---`);
    console.log(`Flip Credits: ${formatEther(affiliateFlipCredits)} BURNIE`);
    console.log(`BURNIE Balance: ${formatEther(affiliateBurnie)} BURNIE`);

    console.log("\n✓ Full simulation complete (Level 12)!\n");
  });
});
