import { expect } from 'chai';
import hre from 'hardhat';
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

// The shared cross-repo fixture, generated by an independent scalar reference, replayed
// through the compiled production harness. Consumers replay the same file.
const FIXTURE = 'test/fixtures/degenerette-wild-vectors.json';
const RESULT_TICKET_TAG = 0x446567656e526573756c74n;
const WWXRP_DRAW_TAG = 0x575758525044726177n;
const WWXRP_RIG_SALT = 0x52494721n;
const BET_SURVIVAL_TAG = 0x446567656e537572766976616cn;
const BOX_SURVIVAL_TAG = 0x537572766976616cn;

describe('Degenerette wild-color shared vectors', function () {
  const { ethers } = hre;
  const coder = ethers.AbiCoder.defaultAbiCoder();
  const hashN = (...xs) => BigInt(ethers.keccak256(coder.encode(xs.map(() => 'uint256'), xs)));
  const v = JSON.parse(readFileSync(FIXTURE, 'utf8'));
  let h;
  before(async function () { h = await (await ethers.getContractFactory('DegeneretteMathHarness')).deploy(); });

  it('is the generator output (not stale)', function () {
    execFileSync('python3', ['-B', v.generator, '--check'], { encoding: 'utf8' });
  });

  it('producers: ordinary and house lanes', async function () {
    for (const p of v.producers) {
      expect(await h.ordinaryTraits(BigInt(p.rand))).to.equal(BigInt(p.ordinary));
      expect(await h.traits(BigInt(p.rand))).to.equal(BigInt(p.house));
    }
  });

  it('paid bet spins: streams, score, wilds, tail byte and payouts', async function () {
    for (const b of v.bet_spins) {
      const word = BigInt(b.word);
      const seed = hashN(word, BigInt(b.index), BigInt(b.symbol), BigInt(b.spin));
      const houseSeed = BigInt(b.spin === 0
        ? ethers.solidityPackedKeccak256(['uint256', 'uint32', 'bytes1'], [word, b.index, '0x51'])
        : ethers.solidityPackedKeccak256(['uint256', 'uint32', 'uint8', 'bytes1'], [word, b.index, b.spin, '0x51']));
      const [player, house, score, wilds] = await h.spin(seed, houseSeed, b.symbol, 0);
      expect(player).to.equal(BigInt(b.player));
      expect(house).to.equal(BigInt(b.house));
      expect(Number(score)).to.equal(b.score);
      expect(Number(wilds)).to.equal(b.wilds);
      expect(b.score | (b.wilds << 4)).to.equal(b.tail_byte);
      expect(await h.payout(b.score, b.wilds, 0, BigInt(b.eth_stake_wei), b.activity)).to.equal(BigInt(b.eth_payout_wei));
      expect(await h.payout(b.score, b.wilds, 1, BigInt(b.flip_stake), b.activity)).to.equal(BigInt(b.flip_payout_pre_survival));
      expect(BigInt(b.player) & ~0xffffffffn).to.equal(0n);
      expect(await h.ticket(hashN(word, BigInt(b.index), BigInt(b.symbol), BigInt(b.spin)), b.symbol)).to.equal(BigInt(b.player));
    }
  });

  it('FLIP survival outcomes', function () {
    for (const s of v.flip_survival) {
      const bit = hashN(BigInt(s.word), BigInt(s.owner), BigInt(s.bet_id), BET_SURVIVAL_TAG) & 1n;
      expect(bit === 1n).to.equal(s.survives);
    }
  });

  it('box spins: WWXRP draw domain, natural reel, help and payouts', async function () {
    for (const b of v.box_spins) {
      const spinSeed = BigInt(b.spin_seed);
      if (b.award_seed !== null) expect(hashN(BigInt(b.award_seed), WWXRP_DRAW_TAG)).to.equal(spinSeed);
      const houseSeed = hashN(spinSeed, RESULT_TICKET_TAG);
      const [player, house, score, wilds] = await h.spin(spinSeed, houseSeed, b.symbol, b.currency);
      expect(player).to.equal(BigInt(b.player));
      expect(house).to.equal(BigInt(b.house));
      expect(Number(score)).to.equal(b.score);
      expect(Number(wilds)).to.equal(b.wilds);
      expect(await h.hero(spinSeed, b.symbol)).to.equal(BigInt(b.hero));
      expect(await h.traits(houseSeed)).to.equal(BigInt(b.natural_house));
      if (b.currency === 3) {
        const rigged = await h.rig(BigInt(b.player), BigInt(b.natural_house), b.hero >> 3, hashN(spinSeed, WWXRP_RIG_SALT));
        expect(rigged).to.equal(BigInt(b.house));
        expect(rigged !== BigInt(b.natural_house)).to.equal(b.help_applied);
      }
      expect(await h.payout(b.score, b.wilds, b.currency, BigInt(b.stake), b.activity)).to.equal(BigInt(b.raw_payout));
    }
    expect(v.box_spins.some((b) => b.help_applied)).to.equal(true);
    expect(v.box_spins.some((b) => b.score === 9)).to.equal(true);
  });

  it('FLIP box chain: per-spin reels and the BoxSpin packing', async function () {
    const c = v.flip_box_chain;
    const seed = BigInt(c.box_seed);
    let packed = 0n;
    for (let i = 0; i < 3; ++i) {
      const ss = hashN(seed, BigInt(i));
      const s = c.spins[i];
      expect(ss).to.equal(BigInt(s.spin_seed));
      const [player, house, score, wilds] = await h.spin(ss, hashN(ss, RESULT_TICKET_TAG), 32, 1);
      expect(player).to.equal(BigInt(s.player));
      expect(house).to.equal(BigInt(s.house));
      expect(Number(score)).to.equal(s.score);
      expect(Number(wilds)).to.equal(s.wilds);
      packed |= (player | (house << 32n) | (BigInt(score) << 64n)) << BigInt(72 * i);
    }
    const survived = (hashN(seed, BOX_SURVIVAL_TAG) & 1n) === 1n;
    expect(survived).to.equal(c.survived);
    packed |= (3n << 216n) | (survived ? 1n << 224n : 0n);
    expect(packed).to.equal(BigInt(c.packed_spins));
  });
});
