// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// AUTO-GENERATED by test/deploy-constants.test.js
// Do not edit by hand; regenerate via the test.
library ContractAddresses {
    address internal constant ICONS_32 = 0x5FbDB2315678afecb367f032d93F642f64180aa3;
    address internal constant TROPHY_SVG_ASSETS = 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512;
    address internal constant GAME_MINT_MODULE = 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0;
    address internal constant GAME_JACKPOT_MODULE = 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9;
    address internal constant GAME_BOND_MODULE = 0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9;
    address internal constant GAME_ENDGAME_MODULE = 0x5FC8d32690cc91D4c39d9d3abcBD16989F875707;
    address internal constant DGNRS = 0x0165878A594ca255338adfa4d48449f69242Eb8F;
    address internal constant BONDS = 0xa513E6E4b8f2a923D98304ec87F64353C4D5C853;
    address internal constant COIN = 0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6;
    address internal constant VAULT = 0x8A791620dd6260079BF849Dc5567aDC3F2FdC318;
    address internal constant AFFILIATE = 0x610178dA211FEF7D417bC0e6FeD39F05609AD788;
    address internal constant JACKPOTS = 0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e;
    address internal constant QUESTS = 0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0;
    address internal constant ICON_COLOR_REGISTRY = 0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82;
    address internal constant RENDERER_REGULAR = 0x9A676e781A523b5d0C0e43731313A708CB607508;
    address internal constant RENDERER_TROPHY_SVG = 0x0B306BF915C4d645ff596e518fAf3F9669b97016;
    address internal constant RENDERER_TROPHY = 0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1;
    address internal constant GAMEPIECE_RENDERER_ROUTER = 0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE;
    address internal constant TROPHY_RENDERER_ROUTER = 0x68B1D87F95878fE05B998F19b66F4baba5De1aed;
    address internal constant TROPHIES = 0x3Aa5ebB10DC797CAC828524e59A333d0A371443c;
    address internal constant GAMEPIECES = 0xc6e7DF5E7b4f2A278906862b61205850344D4e7d;
    address internal constant GAME = 0x59b670e9fA9D0A427751Af201D676719a970857b;
    address internal constant ADMIN = 0x4ed7c70F96B99c776995fB64377f0d4aB3B0e1C1;
    address internal constant STETH_TOKEN = 0x8464135c8F25Da09e49BC8782676a84730C318bC;
    address internal constant LINK_TOKEN = 0x71C95911E9a5D330f4D621842EC243EE1343292e;
    address internal constant CREATOR = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
}
